In [55]:
import pandas as pd
import numpy as np
movie = pd.read_csv("../data/movies_processed.csv")
ratings = pd.read_csv("../data/ratings_processed.csv")
users = pd.read_csv("../data/users_processed.csv")

In [ ]:
users_movies_id = ratings[ratings['userId'] == 1]['movieId'].values
users_movie = movie[movie['movieId'].isin(users_movies_id)]
genre_movies_id = users_movie[users_movie['Action'] == 1]['movieId'].values
movies_count = len(genre_movies_id)
genre_mean = ratings[(ratings['userId'] == 1) & (ratings['movieId'].isin(genre_movies_id))]['rating'].mean()

np.float64(4.2)

In [17]:
movie

,movieId,release_year,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,1995,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1,2,1995,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0
2,3,1995,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
3,4,1995,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0
4,5,1995,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3878,3948,2000,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
3879,3949,2000,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
3880,3950,2000,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
3881,3951,2000,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
3882,3952,2000,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0

In [57]:
users[users['userId'] == 1]

   userId  age  occupation  F  M
0       1    1          10  1  0